objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Competitor_1_Price__c</fullName>
        <label>Competitor 1 Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_1__c</fullName>
        <label>Competitor 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor_2_Price__c</fullName>
        <label>Competitor 2 Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_2__c</fullName>
        <label>Competitor 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor_3_Price__c</fullName>
        <label>Competitor 3 Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Competitor_3__c</fullName>
        <label>Competitor 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Competitor</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/globalValueSets/Competitor.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Amazon</fullName>
    </customValue>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Microsoft</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Yahoo</fullName>
    </customValue>
    <masterLabel>Competitor</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadCompetitorTest.cls
@isTest
public class LeadCompetitorTest {

    @isTest static void updateLead() {
        Lead myLead = new Lead();
        myLead.FirstName = 'David';
        myLead.LastName = 'Louis';
        myLead.Company = 'toto';
        myLead.competitor_1__c='Yahoo';
        myLead.competitor_2__c='Salesforce';
        myLead.competitor_3__c='Oracle';
        myLead.Competitor_1_Price__c=123;
        myLead.Competitor_2_Price__c=436;
        myLead.Competitor_3_Price__c=987;
        insert myLead;
        myLead.Company = 'Dell';
        update myLead;
    }
}